### ISSUE TITLE
1.1.0 does not compile

### ISSUE THREAD

**Issue by mwarning** [dakhnod/Meshenger#13]
Hi, I tried to compile the new version.
Android Studio complains that `MeshengerActivity` is not defined. Is the file missing? Renaming the name back to AppCompatActivity solved the issue.
Also a file `app/src/main/res/values/attrs.xml` seems to be needed:

```
<declare-styleable name="CustomStyle">
    <attr name="primaryTextColor" format="reference"/>
    <attr name="secondaryTextColor" format="reference"/>
    <attr name="backgroundCardColor" format="reference"/>
</declare-styleable>
```
This makes Android Studio happy again. :-)

**Comment by dakhnod** [comment]
it seems like i forgot to push that file for some reason, i will have a look at it later...

**Comment by dakhnod** [comment]
would you mind testing it again?

**Comment by mwarning** [comment]
works
