### ISSUE TITLE
Is this project similar to briarproject?

### ISSUE THREAD

**Issue by ovizii** [dakhnod/Meshenger#14]
Hi there,

this project looks great but after having a closer looks it looks like a slimmed-down version of https://briarproject.org/how-it-works.html which seems to have already implemented communication over bluetooth/wifi/tor 

or am I missing some key difference here?

**Comment by licaon-kter** [comment]
This is voice&video over LAN.... Briar is text/files over Tor over Internet. 

How did you take this closer look exactly?


/close as invalid?

**Comment by ovizii** [comment]
> How did you take this closer look exactly?
*Facepalm*
My only excuse it is that it is late and I should go to sleep.
