### ISSUE TITLE
Logo offer for meshenger

### ISSUE THREAD

**Issue by familqasimov** [dakhnod/Meshenger#2]
Hi sir Danieli. I'm graphic designer. I would like to offer logo. If you like, I can give you with great pleasure all the formats of the design free. If you want a change please specify.

![untitled-1](https://user-images.githubusercontent.com/36432269/42730619-05f9b72c-880a-11e8-9104-1712705478d1.png)

**Comment by dakhnod** [comment]
Hi,
i am glad you like to participate in my project, that is nice work!
May i know the idea behind the logo? What connection does it have to the general idea?

**Comment by familqasimov** [comment]
Hello.
I think the logic is straightforward. This app is a software developed for voice contact and video chat. Based on this, I used symbols that symbolize voice and video on the logo. Do you agree with me?

![idea](https://user-images.githubusercontent.com/36432269/42740927-70fdcbee-88be-11e8-841f-37eb5de81273.png)


Best regard
Famil

**Comment by mwarning** [comment]
Maybe some background information. The apps objective is to allow direct communication without the need for servers or Internet.

**Comment by dakhnod** [comment]
Thanks for your explanation, that is an awesome idea and concept!
Yet, when it comes to my project idea, it does not really hit the nail on the head.
My app does not try to say "hey, you can make video and audio calls with me!",
it tries to say "you can make any kind of call without having a server involved in it, thus without anyone seeing or storing your data!".
That statement, and the context of Freifunk was the motivation behind the Icon i developed.

Once again, i really appreciate you trying to help me, and that was a very cool logo,
but it does not really fit my needs.

**Comment by familqasimov** [comment]
I really want to be actively involved in this project. I'll send you 4 logos representing the main idea of the software. I hope you will like one of these. If you still want to make a change, please.

![versions](https://user-images.githubusercontent.com/36432269/42837549-6b9c51a0-8a0f-11e8-97e2-af94c7f80e68.png)

Best regard
Famil

**Comment by mwarning** [comment]
Hi, thanks for the effort. But WiFi plays an important role in the use case. I also do not understand the crossed Internet Explorer logo. my2cents.

**Comment by thereyougo** [comment]
I would change proposed logo4: 

* eliminate  slash e
* keep the tiny eye bubbles in corners, pointing a tail towards center logo THROUGH 4 different condition icons, respectively
** wifi, lte, ?, no sign

* the center icon will have four tails reaching through conditions to tiny eye bubbles

optionally change black center with white highlight to oviod white, inner black ring to megaphone with 3 sound rays

**Comment by thereyougo** [comment]
no easy edit on android afaik..


https://raw.githubusercontent.com/yshrsmz/monotweety/master/assets/header.png

or change center of eye ovoid to above pacman but again with speaking lines

https://media.istockphoto.com/vectors/megaphone-bullhorn-line-icon-outline-vector-sign-linear-style-on-vector-id701066318

https://t3.ftcdn.net/jpg/00/99/64/12/240_F_99641263_ykawxvvnQMYnVbHsdAjkiDrjvdCRhQJW.jpg

**Comment by thereyougo** [comment]
@familqasimov

**Comment by dakhnod** [comment]
@thereyougo i am having difficulties understanding your idea.
I really see no point in outlining LTE, since the app only uses WiFi.
Could you maybe upload a sketch of your idea?

**Comment by familqasimov** [comment]
Hi Daniel. I have some work. I will contact you as soon as possible.

Best regard

22 avq 2018, Çərş. 17:14 tarixində Daniel Dakhno <notifications@github.com>
yazdı:
