### ISSUE TITLE
QR code is partly covered.

### ISSUE THREAD

**Issue by quinreis** [dakhnod/Meshenger#25]
The QR code is partly covered by the "share" icon, so it fails to scan with another phone. See screenshot![Screenshot_20190702-163944_Meshenger](https://user-images.githubusercontent.com/29644810/60521742-1169c180-9ce8-11e9-9ec9-95e3fc6faacd.jpg)
.

**Comment by iamvasuh** [comment]
This issue has been fixed in this link: [QR-Code Presenter](https://github.com/meshenger-app/meshenger-android/commit/39a8734d118dc7e47e865bd2e7c92d034966b191)

**Comment by quinreis** [comment]
I will try it out, but I am not sure how to put together the .apk file, as I had just downloaded it from F-droid.

**Comment by iamvasuh** [comment]
I can send you a .apk file

**Comment by mwarning** [comment]
@quinreis Can you check if this is still a problem? https://github.com/meshenger-app/meshenger-android/releases/tag/v2.0.0 - thanks.

**Comment by ghost** [comment]
The issue is resolved. :-)
