### ISSUE TITLE
Make Meshenger available in F-Droid

### ISSUE THREAD

**Issue by bodems** [dakhnod/Meshenger#4]
It would be great if Meshenger would be availiable in F-Droid!
https://f-droid.org/

**Comment by mwarning** [comment]
https://f-droid.org/en/packages/d.d.meshenger/

It's available.

**Comment by mwarning** [comment]
.. but the logo is missing when the app is shown in f-droid.

**Comment by licaon-kter** [comment]
@mwarning The icon? I can see it just fine, both in app and on site. Did you pull all the download sliders (Wi-Fi & mobile data) to the right in F-Droid settings?

**Comment by mwarning** [comment]
I have enabled "Only on Wi-Fi" in the f-droid settings. f-droid is version 1.3.1.

Anyway, when I search for mesh in f-droid, I get Meshenger as the first result but with a generic f-droid logo in front, the second result is "Tinc App", but it has a proper icon as do the following results.

The detailed info page for Meshenger also lacks the logo. The Meshenger installation works without problems.

**Comment by mwarning** [comment]
I uninstalled f-droid, but now I see that the download link for the f-droid apk is broken. xD

**Comment by mwarning** [comment]
I've found an alternative source. The icon was shown after a minute after the repo was updated. All good now.

**Comment by dakhnod** [comment]
i also experienced some strange things with f-droid, the icon only got shown in the web version or depending on the device language.
