### ISSUE TITLE
Problem adding contact

### ISSUE THREAD

**Issue by Offliner33** [dakhnod/Meshenger#7]
The issue occures when I try to add my devices to each others contact list. The devices I have is an Sony Xperia Z5 running Android 7 and an Sony Xperia XZ Premium running Android 8.

The Sony Xperia Z5 have no problems adding contacts, but the Sony Xperia XZ Premium seems to have an issue as the other contact shows up in the list but it's also always showing an icon next to the contacts name indicating it is trying to contact the other devices. In this state I can only remove the other contact. No connection can be made.

**Comment by mwarning** [comment]
@Offliner33 I noticed that you can still call a contact even when it is not shown online. Looks like the ping can get lost, but the connection will be able to succeed anyway.

**Comment by Offliner33** [comment]
After further testing, it became clear that adding contacts was not the issue. My devices couldn't start a call no matter what I did. They didn't even acknowledge eachother. Just as a quick test, I connected both devices to another router and voila, it worked right away. So the problem wasn't your app, it was my router.

**Comment by dakhnod** [comment]
@mwarning exactly, i decided to make it possible to start a call even if the contact is not pingable, since the ping may fail although the device is online.

**Comment by mwarning** [comment]
@dakhnod sounds good.
