### ISSUE TITLE
Duplicate app

### ISSUE THREAD

**Issue by lil5** [dakhnod/Meshenger#8]
How is this different than Ring
https://f-droid.org/app/cx.ring
https://ring.cx/

**Comment by licaon-kter** [comment]
Ring works on the internet, and other things.

**Comment by mwarning** [comment]
@lil5 thanks for sharing. Ring sounds very good! But it will hardly work without Internet (if at all) and finding bootstrap peers can be problematic. It would be nice if Ring can be extended to use multiple means to find contacts. But so far it probably only uses a DHT.

**Comment by lil5** [comment]
@mwarning I believe ring can run on local networks without internet (might be wrong)

**Comment by lil5** [comment]
Side note heard of briar?
Briar - https://briarproject.org/

**Comment by mwarning** [comment]
yes, but Briar does have problems finding contact on local network since it only supports IPv4. Also, Briar does not support audio/video (yet). But using Tor on the Internet might indicated that it will never support that, because of the latency.
